language: php
branches:
  only:
    - master
    - deploy
cache:
  yarn: true
  directories:
    - "$HOME/.composer/cache/files"
    - "./bin/.phpunit"
    - "$HOME/.symfony"
env:
  global:
    - SYMFONY_PHPUNIT_DIR=./bin/.phpunit
    - SYMFONY_DEPRECATIONS_HELPER=9
    - ACTION="install"
    - PATH="$HOME/.symfony/bin:$PATH"

addons:
  ssh_known_hosts: access818669403.webspace-data.io

jobs:
  fast_finish: true
  include:
    - php: 7.3

before_install:
  - phpenv config-rm xdebug.ini || true
  - '[[ -z $STABILITY ]] || composer config minimum-stability "$STABILITY"'
  - '[[ -z $SYMFONY ]] || composer config extra.symfony.require "$SYMFONY"'
  - if symfony self:version; then symfony self:update --yes ; else wget https://get.symfony.com/cli/installer -O - | bash ; fi

install:
  - php -r "echo ini_get('memory_limit').PHP_EOL;"
  - COMPOSER_MEMORY_LIMIT=-1 composer $ACTION
  - "./bin/phpunit install"

script:
  - "./bin/phpunit"
  - '[[ $TRAVIS_PHP_VERSION != "7.4" ]] || ./vendor/bin/php-cs-fixer fix --diff --dry-run -v'
  - "./bin/console lint:yaml config --parse-tags"
  - "./bin/console lint:twig templates --env=prod"
  - "./bin/console lint:xliff translations"
  - "./bin/console lint:container"

before_deploy:
  - openssl aes-256-cbc -K $encrypted_677fc5c2cfeb_key -iv $encrypted_677fc5c2cfeb_iv -in .travis/id_rsa_travis.enc -out .travis/id_rsa_travis -d
  - eval "$(ssh-agent -s)"
  - chmod 600 .travis/id_rsa_travis
  - ssh-add .travis/id_rsa_travis

deploy:
  provider: script
  skip_cleanup: true
  script: bash .travis/deploy.sh
  on:
    branch: deploy