services:
  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: kamilabs-php
    volumes:
      - .:/app
    working_dir: /app
    networks:
      - kamilabs-network
    environment:
      DATABASE_URL: mysql://symfony:symfony@mysql:3306/kamilabs?server_version=mariadb-10.7

  nginx:
    image: nginx:latest
    container_name: kamilabs-nginx
    ports:
      - "80:80"
    volumes:
      - .:/app  # Utilise /app comme workdir
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - kamilabs-network

  node:
    image: node:14-alpine
    container_name: kamilabs-node
    volumes:
      - .:/app  # Utilise /app comme workdir
    working_dir: /app
    command: sh -c "yarn install && yarn run build"
    networks:
      - kamilabs-network

  mysql:
    image: mariadb:10.7
    container_name: kamilabs-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kamilabs
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - kamilabs-network

networks:
  kamilabs-network:
    driver: bridge
volumes:
  mysql_data: