#index:
#    path: /
#    controller: App\Controller\DefaultController::index
homepage:
  path:         /
  controller:   Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: static/homepage.html.twig